# Generated by Django 4.0 on 2022-01-18 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countrie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(default='DEFAULT VALUE', max_length=40)),
            ],
            options={
                'ordering': ['country_name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_name', models.CharField(default='DEFAULT VALUE', max_length=30)),
            ],
            options={
                'ordering': ['depart_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('hire_date', models.DateField()),
                ('salary', models.IntegerField()),
                ('commission_pct', models.IntegerField()),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb.department')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=35)),
                ('min_salaty', models.IntegerField()),
                ('max_salary', models.IntegerField()),
            ],
            options={
                'ordering': ['job_title'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=25)),
            ],
            options={
                'ordering': ['region_name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=25)),
                ('postal_code', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=30)),
                ('state_province', models.CharField(max_length=12)),
                ('countries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb.countrie')),
            ],
            options={
                'ordering': ['street_address'],
            },
        ),
        migrations.CreateModel(
            name='Job_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb.department')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb.employee')),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb.job')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb.job'),
        ),
        migrations.AddField(
            model_name='department',
            name='locations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb.location'),
        ),
        migrations.AddField(
            model_name='countrie',
            name='regions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb.region'),
        ),
    ]
