# Generated by Django 4.0 on 2022-02-21 15:01

import builtins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('kb', '0005_author_alter_employee_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='author',
            field=models.ForeignKey(default=builtins.id, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
